# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 03:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mcapi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_id', models.IntegerField(default=0)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mcapi.User')),
            ],
        ),
        migrations.RenameField(
            model_name='emails',
            old_name='user',
            new_name='contact',
        ),
        migrations.RenameField(
            model_name='phone',
            old_name='user',
            new_name='contact',
        ),
    ]
