# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-11 03:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcapi', '0002_auto_20170611_0312'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contact',
            new_name='Contacts',
        ),
        migrations.RenameModel(
            old_name='Phone',
            new_name='Phones',
        ),
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
    ]
