# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 06:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mcapi', '0004_auto_20170611_0414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacts',
            name='company',
        ),
    ]
