# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-12 12:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcapi', '0005_remove_contacts_company'),
    ]

    operations = [
        migrations.AddField(
            model_name='emails',
            name='user_phone',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='phones',
            name='user_phone',
            field=models.CharField(default='', max_length=50),
        ),
    ]
