# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-14 16:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mcapi', '0011_auto_20170612_1202'),
    ]

    operations = [
        migrations.RenameField(
            model_name='emails',
            old_name='user_phone',
            new_name='user_token',
        ),
        migrations.RenameField(
            model_name='phones',
            old_name='user_phone',
            new_name='user_token',
        ),
        migrations.AddField(
            model_name='users',
            name='user_token',
            field=models.CharField(default='', max_length=40),
        ),
    ]
